name: Selenium Automation for PDF Export

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run Selenium automation script
        run: |
          python main.py
